web/designer/urls.py
from django.urls import path
from designer import views

app_name = "designer"
urlpatterns = [
    path('', views.designer, name='designer'),
    path('<int:form_id>/', views.designerID, name='designerID'),

    
    path('api/list_databases/', views.list_databases, name='list_databases'),
    path('api/db_tables/', views.db_tables, name='db_tables'),
    path('api/db_table_columns/', views.db_table_columns, name='db_table_columns'),

    path('api/change/', views.change, name="change"),
    path('api/check_name/', views.check_name, name="check_name"),
    path('api/new_form/', views.new_form, name='new_form'), 
    path('api/save/', views.save, name="save"),
    path('api/editable_forms/', views.editable_forms, name="editable_forms"),    
    path('api/upload_form_asset/', views.upload_form_asset, name='upload_form_asset'),
    path('api/get_form/<int:pk>/', views.get_form, name="get_form"),
    path('api/get_editable_form/<int:pk>/', views.get_editable_form, name="get_editable_form"),
    path('api/list_form_assets/<int:pk>/', views.list_form_assets, name="list_form_assets"),
    path('api/list_form_assets/<int:pk>/<str:name>/', views.list_form_assets, name="list_form_assets"),
    path('api/form_content/<int:pk>/', views.form_content, name="form_content"),
    path('api/delete_temp/', views.delete_temp, name="delete_temp"),
    path('api/remove_form_asset/', views.remove_form_asset, name="remove_form_asset"),
    path('api/download/<int:pk>/', views.download, name="download"),

    # tables
    path('api/get_table/<int:form>/<str:table>/', views.get_table, name="get_table"),
    path('api/list_table_columns/<int:form>/<str:table>/', views.list_table_columns, name="list_table_columns"),
    path('api/get_table_column/<int:form>/<str:table>/<str:column>/', views.get_table_column, name="get_table_column"),

    # databases
    path('api/list_dbs/', views.list_dbs, name="list_dbs"),
    path('api/list_db_tables/<str:db>/', views.list_db_tables, name="list_db_tables"),
    path('api/list_db_table_cols/<str:db>/<str:table>/', views.list_db_table_cols, name="list_db_table_cols"),
    path('api/get_db_table_col/<str:db>/<str:table>/<str:column>/', views.get_db_table_col, name="get_db_table_col"),
    path('api/get_db_table_col_unique/<str:db>/<str:table>/<str:column>/', views.get_db_table_col_unique, name="get_db_table_col_unique"),

    # queries
    path('api/list_queries/', views.list_queries, name="list_queries"),

]

web/formsmanager/urls.py
from django.urls import path
from formsmanager import views

app_name = "formsmanager"
urlpatterns = [
    path('', views.formsmanager, name='formsmanager'),    

    path('api/use/', views.use, name="use"),
    path('api/disable/', views.disable, name="disable"),
    path('api/delete/', views.delete, name="delete"),    
    path('api/delete_temps/', views.delete_temps, name="delete_temps"),
    path('api/clone/', views.clone, name="clone"),    
    path('api/forms/', views.forms, name="forms"),    

]

web/help/urls.py
from django.urls import path
from help import views

app_name = "help"
urlpatterns = [
    #path('', views.help, name='help'),
    #path('designer/', views.designer, name='designer'),
    #path('manager/', views.manager, name='manager'),
    #path('app/', views.app, name='app'),
    #path('operations/', views.operations, name='operations'),
    path('api/', views.api, name='api'),
    #path('faq/', views.faq, name='faq'),
    path('examples/', views.examples, name='examples'),
    path('videos/', views.videos, name='videos'),

]

web/idrisk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

#from idrisk.views import handler404, handler500
from django.conf.urls import handler404, handler500

#from idrisk import views

from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pwa.urls')),
    #path('api-token-auth/', views.obtain_auth_token, name='api-tokn-auth'),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('applications/', TemplateView.as_view(template_name='applications.html'), name='applications'),
    
    path('designer/', include('designer.urls')),
    path('preview/', include('preview.urls')),
    path('formsmanager/', include('formsmanager.urls')),
    path('sform/', include('sform.urls')),
    path('operations/', include('operations.urls')),
    path('opeditview/', include('opeditview.urls')),    
    path('help/', include('help.urls')),
    path('rest/', include('rest.urls')),
    path('files/', include('files.urls')),


    # for locale
    path('i18n/', include('django.conf.urls.i18n')),

	path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/icons/favicon.ico'))),

    path('desert/', TemplateView.as_view(template_name='error_pages/desert.html'), name='desert'),
    # only for testing ... remove it when deploy
    #path('404/',handler404, name="handler404"),
    #path('500/',handler500, name="handler500"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'idrisk.views.handler404'
handler500 = 'idrisk.views.handler500'

#handler403 = 'mysite.views.my_custom_permission_denied_view'
#handler400 = 'mysite.views.my_custom_bad_request_view'

# auth urls:
# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

web/operations/urls.py
from django.urls import path

from operations import views

app_name = "operations"
urlpatterns = [
    path('', views.operations, name='operations'),

    path('api/list_in_use_forms/', views.list_in_use_forms, name="list_in_use_forms"),
    path('api/exec_query/', views.exec_query, name="exec_query"),
    path('api/new_operation/', views.new_operation, name="new_operation"),
    path('api/delete_operation/', views.delete_operation, name="delete_operation"),
    path('api/update_operation/', views.update_operation, name="update_operation"),
    path('api/new_operation_complete/', views.new_operation_complete, name="new_operation_complete"),
    path('api/get_operation/<int:pk>/', views.get_operation, name="get_operation"),
    path('api/list_operations/<str:stats>/', views.list_operations, name="list_operations"),
    path('api/list_all_operations/', views.list_all_operations, name="list_all_operations"),
    path('api/list_non_completed_operations/', views.list_non_completed_operations, name="list_non_completed_operations"),
    path('api/list_all_non_completed_operations/', views.list_all_non_completed_operations, name="list_all_non_completed_operations"),
    path('api/get_operation_data/<int:pk>/', views.get_operation_data, name="get_operation_data"),
    path('api/set_operation_status/', views.set_operation_status, name="set_operation_status"),
    path('api/get_operation_form_data/<int:pk>/', views.get_operation_form_data, name="get_operation_form_data"),
    path('api/upload_operation_asset/', views.upload_operation_asset, name='upload_operation_asset'),
    path('api/upload_operation_asset_complete/', views.upload_operation_asset_complete, name='upload_operation_asset_complete'),    
    path('api/remove_operation_asset/', views.remove_operation_asset, name="remove_operation_asset"),
    path('api/validate_operation_inputs/<int:pk>/', views.validate_operation_inputs, name="validate_operation_inputs"),
    path('api/get_op_form_data/<int:pk>/', views.get_op_form_data, name="get_op_form_data"),
    path('api/list_operation_assets/<int:pk>/', views.list_operation_assets, name="list_operation_assets"),    
    path('api/list_operation_assets/<int:pk>/<str:name>/', views.list_operation_assets, name="list_operation_assets"),
    path('api/list_operation_annexes/<int:pk>/', views.list_operation_annexes, name="list_operation_annexes"),
    path('api/download_asset/<int:pk>/', views.download_asset, name="download_asset"),
    path('api/clean_operation_assets/', views.clean_operation_assets, name="clean_operation_assets"),
    path('api/is_operation_signed/<int:pk>/', views.is_operation_signed, name="is_operation_signed"),

]

web/sform/urls.py
from django.urls import path
from sform import views

app_name = "sform"
urlpatterns = [
    path('', views.sform, name='sform'),
]

web/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">{% trans "Home" %}</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">{% trans "Admin" %}</a>
        </li>
    </ul>
<!--
    {% block nav_bar_center %}
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    {% endblock %}
 -->
    {% block nav_custom_menu %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <ul class="nav navbar-nav">
            {% block header_dropdowns %}
            

            <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="navbarConfigurations" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                <span id="selected-language" class='flag-icon flag-icon-{% if LANGUAGE_CODE == "en" %}gb{% else %}{{LANGUAGE_CODE}}{% endif %}'>
                </span> 
                {% trans "Language" %}				
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarConfigurations">
                    <a data-lang= "en" class="dropdown-item language-select" href="javascript:void(0);">
                        <span class="flag-icon flag-icon-gb">
                        </span> 
                        English
                    </a>        
                    <a data-lang= "pt" class="dropdown-item language-select" href="javascript:void(0);">
                        <span class="flag-icon flag-icon-pt">
                        </span> 
                        Portugues
                    </a>
                    <a data-lang= "hr" class="dropdown-item language-select" href="javascript:void(0);">
                        <span class="flag-icon flag-icon-hr">
                        </span> 
                        Hrvatski
                    </a>
                </div>
            </li> 


            {% block user_info %}            
            <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-user fa-2x"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="javascript:void(0)" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{%avatar_url size=128 %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    {% if request.user.is_authenticated %}
                                        <h3 class="dropdown-item-title">
                                                {% firstof request.user.get_short_name request.user.get_username %}
                                            <span class="float-right text-sm text-success"><i class="fa fa-check fa-2x"></i></span>
                                        </h3>
                                        <p class="text-sm"><small>{% trans 'Member since' %} :</small></p>
                                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>  <small>{{ request.user.date_joined }}</small></p>
                                    {% else %}
                                        <span class="float-right text-sm text-danger"><i class="fa fa-times fa-2x"></i></span>
                                        <p>{% trans 'Not Logged in' %}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-footer">
                            {% if request.user.is_authenticated %}
                                <a href="{% block change_password_url %}{% url 'password_change' %}{% endblock %}" class="btn btn-primary btn-sm">{% trans 'Change password' %}</a>
                                <a href="{% url 'logout' %}" class="btn btn-danger btn-sm">{% trans 'Sign out' %}</a>
                                {% else %}
                                <a href="{% url 'login' %}" class="btn btn-success btn-sm btn-block">{% trans 'Sign in' %}</a>
                                {% endif %}
                            </div>
                        
                    </div>
                </li>
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    </ul>
        {% endblock nav_custom_menu %}


<form id="lang-select-form" action="{% url 'set_language' %}" method="post">
  {% csrf_token %}
  <input name="next" type="hidden" value="{{ redirect_to }}" />
  <input id="selected-lang-form" name="language" type="hidden" value="{{LANGUAGE_CODE}}" />
</form>  


{% endblock %}
</nav>

web/templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %} 
{% load static %} 
{% load i18n %}	<!-- translation -->
{% load adminlte_helpers %}
{% load auth_filters %}

{% block logo %}
<a href="/" class="brand-link">
	<img src="{% static 'images/logos/logo_project.png' %}" alt="Project logo" class="brand-image img-square elevation-3" style="opacity: .8">
  {% block logo_text %}<span class="brand-text font-weight-light">FORMS </span>{% endblock %}
</a>
{% endblock %}

{% block user_panel %}
	<!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          	<img src="{% avatar_url size=90 %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
			{% if request.user.is_authenticated %}
          	<a href="javascript:void(0);" class="d-block">{% firstof request.user.get_full_name request.user.username %}</a>
			{% else %}
          	<a href="{% url 'login' %}" class="d-block"><b>{% trans 'Sign in' %}</b></a>
			{% endif %}
        </div>
      </div>
{% endblock %}


{% block nav_heading %}
	{% if request.user.is_authenticated %}
		{% trans 'MAIN' %}
	{% endif %}
{% endblock %}

{% block nav_links %}

{% if request.user.is_authenticated and request.user|has_group:"manager" %}

	<li class="nav-header">{% trans "FORMS" %}</li>

	<li class="nav-item">
		<a href="{% url 'designer:designer' %}" class="nav-link"> <i class="nav-icon fas fa-drafting-compass"></i>
			<p>{% trans 'Designer' %}</p>
		</a>
	</li>
	<li class="nav-item">
		<a href="{% url 'formsmanager:formsmanager' %}" class="nav-link"> <i class="nav-icon fas fa-tasks"></i>
			<p>{% trans 'Forms Manager' %}</p>
		</a>
	</li>

{% endif %}

{% if request.user.is_authenticated %}

	<li class="nav-header">{% trans "OPERATIONS" %}</li>

	{% if request.user|has_group:"manager" %}
		<li class="nav-item">
			<a href="{% url 'operations:operations' %}" class="nav-link"> <i class="nav-icon fas fa-project-diagram"></i>
				<p>{% trans "Operations" %}</p>
			</a>
		</li>
	{% endif %}

	<li class="nav-item">
		<a href="{% url 'sform:sform' %}" class="nav-link"> <i class="nav-icon fas fa-mobile-alt"></i>
			<p>{% trans "App" %}</p>
		</a>
	</li>

	
	<li class="nav-header">{% trans 'HELP' %}</li>

	{% if request.user|has_group:"manager" %}
	<li class="nav-item">
		<a href="{% url 'help:examples' %}" class="nav-link"> <i class="nav-icon fas fa-globe"></i>
			<p>{% trans 'Examples' %}</p>
		</a>
	</li>	
	<li class="nav-item">
		<a href="{% url 'help:api' %}" class="nav-link"> <i class="nav-icon fas fa-exchange-alt"></i>
			<p>{% trans 'Rest API' %}</p>
		</a>
	</li>
	{% endif %}
	<li class="nav-item">
		<a href="{% url 'help:videos' %}" class="nav-link"> <i class="nav-icon fas fa-film"></i>
			<p>{% trans 'Videos' %}</p>
		</a>
	</li>	
	<li class="nav-item">
		<a href="/media/files/users_manual.pdf" class="nav-link"> <i class="nav-icon fas fa-file-pdf"></i>
			<p>{% trans 'Manual' %}</p>
		</a>
	</li>
	

	<li class="nav-header">
		<a href="{% url 'applications' %}">
			<p>{% trans 'APPLICATIONS' %}</p>
		</a>
	</li>	


{% endif %}
{% endblock nav_links %} 